server:
  port: 8080

spring:
  application:
    name: ms-calculator
  datasource:
    url: jdbc:h2:mem:calcDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.orm.connections.pooling: ERROR